"""crm_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django_registration.backends.one_step.views import RegistrationView

from core.views import dashboardjubayer, IndexTemplateView
from users.forms import CustomUserForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/register/",
         RegistrationView.as_view(
             form_class=CustomUserForm,
             success_url="/",
         ), name="django_registration_register"),

    path("accounts/",
         include("django_registration.backends.one_step.urls")),

    path("accounts/",
         include("django.contrib.auth.urls")),
    path("api/",
         include("users.api.urls")),
    path("api-auth/",
         include("rest_framework.urls")),

    path("api/rest-auth/",
         include("rest_auth.urls")),

    path("api/rest-auth/registration/",
         include("rest_auth.registration.urls")),
    path("", IndexTemplateView.as_view(), name="index"),

    # template setup urls
    path('', include('users.urls')),
    path('', include('clients.urls')),
    path('index', TemplateView.as_view(template_name='index.html'), name='index'),
    path('dashboard-2/', TemplateView.as_view(template_name='dashboard/dashboard-2.html'), name='dashboard-2'),
    path('dashboard-3/', TemplateView.as_view(template_name='dashboard/dashboard-3.html'), name='dashboard-3'),
    path('dashboard-4/', TemplateView.as_view(template_name='dashboard/dashboard-4.html'), name='dashboard-4'),
    path('apps-kanbanboard/', TemplateView.as_view(template_name='dashboard/apps-kanbanboard.html'),
         name='apps-kanbanboard'),
    path('apps-calendar/', TemplateView.as_view(template_name='dashboard/apps-calendar.html'), name='apps-calendar'),
    path('apps-contacts/', TemplateView.as_view(template_name='dashboard/apps-contacts.html'), name='apps-contacts'),
    path('apps-projects/', TemplateView.as_view(template_name='dashboard/apps-projects.html'), name='apps-projects'),
    path('apps-tickets/', TemplateView.as_view(template_name='dashboard/apps-tickets.html'), name='apps-tickets'),
    path('apps-companies/', TemplateView.as_view(template_name='dashboard/apps-companies.html'), name='apps-companies'),
    path('crm-dashboard/', TemplateView.as_view(template_name='dashboard/crm-dashboard.html'), name='crm-dashboard'),
    path('crm-contacts/', TemplateView.as_view(template_name='dashboard/client/allClient.html'),
         name='crm-contacts'),
    path('crm-opportunities/', TemplateView.as_view(template_name='dashboard/crm-opportunities.html'),
         name='crm-opportunities'),
    path('crm-leads/', TemplateView.as_view(template_name='dashboard/crm-leads.html'), name='crm-leads'),
    path('crm-customers/', TemplateView.as_view(template_name='dashboard/crm-customers.html'), name='crm-customers'),
    path('ecommerce-dashboard/', TemplateView.as_view(template_name='dashboard/ecommerce-dashboard.html'),
         name='ecommerce-dashboard'),
    path('ecommerce-products/', TemplateView.as_view(template_name='dashboard/ecommerce-products.html'),
         name='ecommerce-products'),
    path('ecommerce-prduct-detail/', TemplateView.as_view(template_name='dashboard/ecommerce-prduct-detail.html'),
         name='ecommerce-prduct-detail'),
    path('ecommerce-product-edit/', TemplateView.as_view(template_name='dashboard/ecommerce-product-edit.html'),
         name='ecommerce-product-edit'),
    path('ecommerce-orders/', TemplateView.as_view(template_name='dashboard/ecommerce-orders.html'),
         name='ecommerce-orders'),
    path('ecommerce-sellers/', TemplateView.as_view(template_name='dashboard/ecommerce-sellers.html'),
         name='ecommerce-sellers'),
    path('layouts-sidebar-user/', TemplateView.as_view(template_name='dashboard/layouts-sidebar-user.html'),
         name='layouts-sidebar-user'),
    path('layouts-sidebar-sm/', TemplateView.as_view(template_name='dashboard/layouts-sidebar-sm.html'),
         name='layouts-sidebar-sm'),
    path('layouts-dark-sidebar/', TemplateView.as_view(template_name='dashboard/layouts-dark-sidebar.html'),
         name='layouts-dark-sidebar'),
    path('layouts-light-topbar/', TemplateView.as_view(template_name='dashboard/layouts-light-topbar.html'),
         name='layouts-light-topbar'),
    path('layouts-preloader/', TemplateView.as_view(template_name='dashboard/layouts-preloader.html'),
         name='layouts-preloader'),
    path('layouts-sidebar-collapsed/', TemplateView.as_view(template_name='dashboard/layouts-sidebar-collapsed.html'),
         name='layouts-sidebar-collapsed'),
    path('layouts-boxed/', TemplateView.as_view(template_name='dashboard/layouts-boxed.html'), name='layouts-boxed'),
    path('email-inbox/', TemplateView.as_view(template_name='dashboard/email-inbox.html'), name='email-inbox'),
    path('email-read/', TemplateView.as_view(template_name='dashboard/email-read.html'), name='email-read'),
    path('email-compose/', TemplateView.as_view(template_name='dashboard/email-compose.html'), name='email-compose'),
    path('email-templates/', TemplateView.as_view(template_name='dashboard/email-templates.html'),
         name='email-templates'),
    path('pages-starter/', TemplateView.as_view(template_name='dashboard/pages-starter.html'), name='pages-starter'),
    path('pages-login/', TemplateView.as_view(template_name='dashboard/pages-login.html'), name='pages-login'),
    path('pages-register/', TemplateView.as_view(template_name='dashboard/pages-register.html'), name='pages-register'),
    path('pages-signin-signup/', TemplateView.as_view(template_name='dashboard/pages-signin-signup.html'),
         name='pages-signin-signup'),
    path('pages-recoverpw/', TemplateView.as_view(template_name='dashboard/pages-recoverpw.html'),
         name='pages-recoverpw'),
    path('pages-lock-screen/', TemplateView.as_view(template_name='dashboard/pages-lock-screen.html'),
         name='pages-lock-screen'),
    path('pages-logout/', TemplateView.as_view(template_name='dashboard/pages-logout.html'), name='pages-logout'),
    path('pages-confirm-mail/', TemplateView.as_view(template_name='dashboard/pages-confirm-mail.html'),
         name='pages-confirm-mail'),
    path('pages-404/', TemplateView.as_view(template_name='dashboard/pages-404.html'), name='pages-404'),
    path('pages-404-alt/', TemplateView.as_view(template_name='dashboard/pages-404-alt.html'), name='pages-404-alt'),
    path('pages-500/', TemplateView.as_view(template_name='dashboard/pages-500.html'), name='pages-500'),
    path('extras-profile/', TemplateView.as_view(template_name='dashboard/profile/myAccount.html'),
         name='extras-profile'),
    path('extras-timeline/', TemplateView.as_view(template_name='dashboard/extras-timeline.html'),
         name='extras-timeline'),
    path('extras-sitemap/', TemplateView.as_view(template_name='dashboard/extras-sitemap.html'), name='extras-sitemap'),
    path('extras-invoice/', TemplateView.as_view(template_name='dashboard/extras-invoice.html'), name='extras-invoice'),
    path('extras-faqs/', TemplateView.as_view(template_name='dashboard/extras-faqs.html'), name='extras-faqs'),
    path('extras-search-results/', TemplateView.as_view(template_name='dashboard/extras-search-results.html'),
         name='extras-search-results'),
    path('extras-pricing/', TemplateView.as_view(template_name='dashboard/extras-pricing.html'), name='extras-pricing'),
    path('extras-maintenance/', TemplateView.as_view(template_name='dashboard/extras-maintenance.html'),
         name='extras-maintenance'),
    path('extras-coming-soon/', TemplateView.as_view(template_name='dashboard/extras-coming-soon.html'),
         name='extras-coming-soon'),
    path('extras-gallery/', TemplateView.as_view(template_name='dashboard/extras-gallery.html'), name='extras-gallery'),
    path('ui-buttons/', TemplateView.as_view(template_name='dashboard/ui-buttons.html'), name='ui-buttons'),
    path('ui-cards/', TemplateView.as_view(template_name='dashboard/ui-cards.html'), name='ui-cards'),
    path('ui-portlets/', TemplateView.as_view(template_name='dashboard/ui-portlets.html'), name='ui-portlets'),
    path('ui-tabs-accordions/', TemplateView.as_view(template_name='dashboard/ui-tabs-accordions.html'),
         name='ui-tabs-accordions'),
    path('ui-modals/', TemplateView.as_view(template_name='dashboard/ui-modals.html'), name='ui-modals'),
    path('ui-progress/', TemplateView.as_view(template_name='dashboard/ui-progress.html'), name='ui-progress'),
    path('ui-notifications/', TemplateView.as_view(template_name='dashboard/ui-notifications.html'),
         name='ui-notifications'),
    path('ui-spinners/', TemplateView.as_view(template_name='dashboard/ui-spinners.html'), name='ui-spinners'),
    path('ui-images/', TemplateView.as_view(template_name='dashboard/ui-images.html'), name='ui-images'),
    path('ui-carousel/', TemplateView.as_view(template_name='dashboard/ui-carousel.html'), name='ui-carousel'),
    path('ui-video/', TemplateView.as_view(template_name='dashboard/ui-video.html'), name='ui-video'),
    path('ui-dropdowns/', TemplateView.as_view(template_name='dashboard/ui-dropdowns.html'), name='ui-dropdowns'),
    path('ui-ribbons/', TemplateView.as_view(template_name='dashboard/ui-ribbons.html'), name='ui-ribbons'),
    path('ui-tooltips-popovers/', TemplateView.as_view(template_name='dashboard/ui-tooltips-popovers.html'),
         name='ui-tooltips-popovers'),
    path('ui-general/', TemplateView.as_view(template_name='dashboard/ui-general.html'), name='ui-general'),
    path('ui-typography/', TemplateView.as_view(template_name='dashboard/ui-typography.html'), name='ui-typography'),
    path('ui-grid/', TemplateView.as_view(template_name='dashboard/ui-grid.html'), name='ui-grid'),
    path('admin-widgets/', TemplateView.as_view(template_name='dashboard/admin-widgets.html'), name='admin-widgets'),
    path('admin-nestable/', TemplateView.as_view(template_name='dashboard/admin-nestable.html'), name='admin-nestable'),
    path('admin-range-slider/', TemplateView.as_view(template_name='dashboard/admin-range-slider.html'),
         name='admin-range-slider'),
    path('admin-animation/', TemplateView.as_view(template_name='dashboard/admin-animation.html'),
         name='admin-animation'),
    path('admin-sweet-alert/', TemplateView.as_view(template_name='dashboard/admin-sweet-alert.html'),
         name='admin-sweet-alert'),
    path('admin-tour/', TemplateView.as_view(template_name='dashboard/admin-tour.html'), name='admin-tour'),
    path('admin-loading-buttons/', TemplateView.as_view(template_name='dashboard/admin-loading-buttons.html'),
         name='admin-loading-buttons'),
    path('icons-feather/', TemplateView.as_view(template_name='dashboard/icons-feather.html'), name='icons-feather'),
    path('icons-mdi/', TemplateView.as_view(template_name='dashboard/icons-mdi.html'), name='icons-mdi'),
    path('icons-dripicons/', TemplateView.as_view(template_name='dashboard/icons-dripicons.html'),
         name='icons-dripicons'),
    path('icons-font-awesome/', TemplateView.as_view(template_name='dashboard/icons-font-awesome.html'),
         name='icons-font-awesome'),
    path('icons-themify/', TemplateView.as_view(template_name='dashboard/icons-themify.html'), name='icons-themify'),
    path('icons-simple-line/', TemplateView.as_view(template_name='dashboard/icons-simple-line.html'),
         name='icons-simple-line'),
    path('icons-weather/', TemplateView.as_view(template_name='dashboard/icons-weather.html'), name='icons-weather'),
    path('forms-elements/', TemplateView.as_view(template_name='dashboard/forms-elements.html'), name='forms-elements'),
    path('forms-advanced/', TemplateView.as_view(template_name='dashboard/forms-advanced.html'), name='forms-advanced'),
    path('forms-validation/', TemplateView.as_view(template_name='dashboard/forms-validation.html'),
         name='forms-validation'),
    path('forms-pickers/', TemplateView.as_view(template_name='dashboard/forms-pickers.html'), name='forms-pickers'),
    path('forms-wizard/', TemplateView.as_view(template_name='dashboard/forms-wizard.html'), name='forms-wizard'),
    path('forms-masks/', TemplateView.as_view(template_name='dashboard/forms-masks.html'), name='forms-masks'),
    path('forms-summernote/', TemplateView.as_view(template_name='dashboard/forms-summernote.html'),
         name='forms-summernote'),
    path('forms-quilljs/', TemplateView.as_view(template_name='dashboard/forms-quilljs.html'), name='forms-quilljs'),
    path('forms-file-uploads/', TemplateView.as_view(template_name='dashboard/forms-file-uploads.html'),
         name='forms-file-uploads'),
    path('forms-x-editable/', TemplateView.as_view(template_name='dashboard/forms-x-editable.html'),
         name='forms-x-editable'),
    path('forms-image-crop/', TemplateView.as_view(template_name='dashboard/forms-image-crop.html'),
         name='forms-image-crop'),
    path('tables-basic/', TemplateView.as_view(template_name='dashboard/tables-basic.html'), name='tables-basic'),
    path('tables-datatables/', TemplateView.as_view(template_name='dashboard/tables-datatables.html'),
         name='tables-datatables'),
    path('tables-editable/', TemplateView.as_view(template_name='dashboard/tables-editable.html'),
         name='tables-editable'),
    path('tables-responsive/', TemplateView.as_view(template_name='dashboard/tables-responsive.html'),
         name='tables-responsive'),
    path('tables-footables/', TemplateView.as_view(template_name='dashboard/tables-footables.html'),
         name='tables-footables'),
    path('tables-bootstrap/', TemplateView.as_view(template_name='dashboard/tables-bootstrap.html'),
         name='tables-bootstrap'),
    path('tables-tablesaw/', TemplateView.as_view(template_name='dashboard/tables-tablesaw.html'),
         name='tables-tablesaw'),
    path('tables-jsgrid/', TemplateView.as_view(template_name='dashboard/tables-jsgrid.html'), name='tables-jsgrid'),
    path('charts-flot/', TemplateView.as_view(template_name='dashboard/charts-flot.html'), name='charts-flot'),
    path('charts-morris/', TemplateView.as_view(template_name='dashboard/charts-morris.html'), name='charts-morris'),
    path('charts-chartjs/', TemplateView.as_view(template_name='dashboard/charts-chartjs.html'), name='charts-chartjs'),
    path('charts-peity/', TemplateView.as_view(template_name='dashboard/charts-peity.html'), name='charts-peity'),
    path('charts-chartist/', TemplateView.as_view(template_name='dashboard/charts-chartist.html'),
         name='charts-chartist'),
    path('charts-c3/', TemplateView.as_view(template_name='dashboard/charts-c3.html'), name='charts-c3'),
    path('charts-sparklines/', TemplateView.as_view(template_name='dashboard/charts-sparklines.html'),
         name='charts-sparklines'),
    path('charts-knob/', TemplateView.as_view(template_name='dashboard/charts-knob.html'), name='charts-knob'),
    path('charts-ricksaw/', TemplateView.as_view(template_name='dashboard/charts-ricksaw.html'), name='charts-ricksaw'),
    path('charts-just-gage/', TemplateView.as_view(template_name='dashboard/charts-just-gage.html'),
         name='charts-just-gage'),
    path('maps-google/', TemplateView.as_view(template_name='dashboard/maps-google.html'), name='maps-google'),
    path('maps-vector/', TemplateView.as_view(template_name='dashboard/maps-vector.html'), name='maps-vector'),
    path('maps-mapael/', TemplateView.as_view(template_name='dashboard/maps-mapael.html'), name='maps-mapael'),

]
