# Generated by Django 3.0.4 on 2020-03-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_unique_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
