# Generated by Django 3.0.4 on 2020-03-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_unique_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Post_code',
            new_name='Zip_code',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telephone No'),
        ),
    ]
