# Generated by Django 3.0.4 on 2020-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200322_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Business_maturity_rate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Maturity Rate'),
        ),
    ]
